### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by huseyinerbayat** [farukcam/kuveytturk#1]
php artisan vendor:publish yaptığımda 
 Class 'Farukcam\Kuveytturk\KuveytturkServiceProvider' not found  hatası alıyorum?

**Comment by farukcam** [comment]
@huseyinerbayat ,
Provider eklemeyi aşağıdaki gibi yapabilir misin?

`farukcam\Kuveytturk\KuveytturkServiceProvider::class`
