### ISSUE TITLE
419 expired alıyorum

### ISSUE THREAD

**Issue by sezginsevinc** [farukcam/kuveytturk#5]
sanırım csrf olmadığı için bilgileri gönderdikten sonra olumlu olumsuz sonuç alınca 419 expired sayfasına yönlendiriyor. Nasıl csrf ekleyebiliriz gelen response a veya nasıl bu linki csrfden hariç tutabiliriz?

**Comment by farukcam** [comment]
`VerifyCsrfToken.php` middlleware dosyasında response olan sayfayı except yapmalısın @expixer

**Comment by sezginsevinc** [comment]
evet denedim sonradan sorun yok şimdi. Gönderdiğimiz bir veriyi geri almanın bir yolu var mı? Merchant id yolluyoruz ancak yanında müşteri id sini gönderip dönüşte yollamasını istiyorum mesela siz başarabildiniz mi? @farukcam

**Comment by farukcam** [comment]
burada şöyle yapabilirsin geri dönüşte gönderdiğin merchant_id `MerchantOrderId` parametresinde geri döner. işlemin başında siparişini bu id ile bir yerde geçici kayıt alarak işlemi sonlandırabilirsin. ben öyle yapmıştım. @expixer
